[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.2"
  NODE_ENV = "production"
  NEXT_PUBLIC_STATIC_EXPORT = "false"  # Disable static export for Netlify Functions
  # Enable the Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Required for Next.js API routes and Server-Side Rendering (SSR)
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Enable static exports for Next.js
    enableStaticExports = false

# Redirect all API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextServer/:splat"
  status = 200
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["en"], Role = ["anonymous", "authenticated"]}

[context.production.environment]
  NODE_VERSION = "18.20.2"
  NODE_ENV = "production"
  NEXT_PUBLIC_STATIC_EXPORT = "false"

[context.deploy-preview.environment]
  NODE_VERSION = "18.20.2"
  NODE_ENV = "development"
  NEXT_PUBLIC_STATIC_EXPORT = "false"

[context.branch-deploy.environment]
  NODE_VERSION = "18.20.2"
  NODE_ENV = "development"
  NEXT_PUBLIC_STATIC_EXPORT = "false"